Accounts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
app_name = "Accounts"

urlpatterns = [
    url("^$",views.loginView,name = "account"),
    url("^signup/$",views.signupView,name = "signup"),
    url("^reset/$",views.resetPassword,name = "reset"),
    url("^activate/$",views.activateAccount,name = "activate"),
    url("^logout/$",views.logoutView,name = "logout"),
]

Blogs/urls.py
from django.conf.urls import url
from . import views

app_name = "Blogs"

urlpatterns = [
    url("^$",views.blogView,name = "blog")
]

Home/urls.py
from django.conf.urls import url
from . import views

app_name = "home"

urlpatterns = [
    url("^$",views.homeView,name = "home"),
    url("^team/$",views.teamView, name = "team"),
    url("^stats/$",views.statsView,name = "stats"),
]

Team/urls.py
from django.conf.urls import url
from . import views

app_name = "Team"

urlpatterns = [
    url("^$",views.teamView,name = "team")
]

virdis/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url("", include("Home.urls")),
    url("^accounts/", include("Accounts.urls")),
    ]

Accounts/models.py
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
from django.db import models

class VrdisManager(BaseUserManager):
    def create_user(self,email,username,password = None,is_admin = False,is_staff = True,is_active = True):
        if username is None:
            raise ValueError("username cannot be None")
        if email is None:
            raise ValueError("email cannot be None")
        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.is_admin = is_admin
        user.is_active = is_active
        user.is_staff = is_staff
        user.save()
        return user

    def create_superuser(self,email,username,password = None):
        user = self.create_user(
        email = email,
        username = username,
        password = password,
        is_active = True,
        is_admin = True,
        is_staff = True,
        )
        return user

class Virdismart(AbstractBaseUser):
    email = models.EmailField(unique = True,max_length = 120)
    username = models.CharField(max_length  =40)
    last_login = models.DateTimeField(auto_now = True)
    is_admin = models.BooleanField(default = False)
    is_staff = models.BooleanField(default = True)
    date_joined = models.DateTimeField(auto_now_add = True)
    is_active = models.BooleanField(default = True)

    USERNAME_FIELD = "email"

    REQUIRED_FIELDS = [
            'username',
    ]

    objects = VrdisManager()

    class Meta:
        db_table = "Accounts"
        
    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.email

    def get_full_name(self):
        return self.email

    def has_perm(self,perm,obj = None):
        return self.is_admin

    def has_module_perms(self,app_label):
        return True

Blogs/models.py
from django.db import models

# Create your models here.

Home/models.py
from django.db import models

# Create your models here.

Team/models.py
from django.db import models

# Create your models here.

Accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

class VirdisForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            'email',
            'username',
            'password1',
            'password2'
        ]

Accounts/views.py
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import render,redirect
from django.core.mail import send_mail
from django.http import HttpResponse
from .models import Virdismart
from .forms import VirdisForm
import json, re
def loginView(request):
    next = request.GET.get('next') if request.GET.get('next') else "/"
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email = email, password = password)

        if user is not None:
            login(request, user)
            return HttpResponse(json.dumps({
                    "redirect":next,
            }),content_type = "application/json")

        else:
            return HttpResponse(json.dumps({
                    "errors":"email or password failed",
            }),content_type = "application/json")

    return render(request,"Accounts/login.html", context = {
    })
def signupView(request):
    if request.method =="POST":
        form = VirdisForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(json.dumps({
                    "redirect":"/accounts/",
            }),content_type = "application/json")
        else:
            return HttpResponse(json.dumps({
                    "errors":form.errors,
            }),content_type = "application/json")

    return render(request, "Accounts/signup.html", context = {

    })

def activateAccount(request):
    if request.method == "POST":
        email = request.POST['email']
        name = re.search(pattern,string)[0].title
        res = send_mail("Account activation",name + " please activate your account here .",email,[],html_message = "")
def resetPassword(request):
    if request.method == "POST":
        email = request.POST['email']
        obj = Virdismart.objects.get(email = email)
        print(email)
        token = PasswordResetTokenGenerator().make_token(obj)
        pattern = "[a-zA-Z]+"
        name = re.search(pattern,email)[0].title
        res = send_mail("Account activation"," please reset your account here "+token,email,[email],html_message = "")
        print(res)
        return HttpResponse(json.dumps({
                "infor":"reset link sent to your email",
        }),content_type = "application/json")
    return render(request, "Accounts/reset.html",context = {

    })


def logoutView(request):
    user = request.user
    if user is not None:
        logout(request)
    return redirect("home:home")

Blogs/views.py
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# @login_required(login_url = "/accounts/")
def blogView(request):
    additional_info = {
        "logged_in": True if request.user.is_authenticated else False
    }
    return render(request, "Home/home.html",context={
        "additional_info":additional_info
    })

Home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import pymongo

def homeView(request):
    additional_info = {
        "logged_in": True if request.user.is_authenticated else False
    }
    return render(request,"Home/home.html",context = {
            "additional_info":additional_info
    })
def get_top_10():
    client = pymongo.MongoClient('mongodb+srv://codem:1100111@virdismart.nx3p6.mongodb.net/Virdsmart?retryWrites=true&w=majority')
    db = client['Virdismart']
    collection_user = db['users']
    top_10 = collection_user.find({},{'_id':0,'fname':1,'lname':1,'points':1,'massThrown':1}).sort('points',-1).limit(10)
    return list(top_10)

# @login_required(login_url = "/accounts/")
def statsView(request):
    additional_info = {
        "logged_in": True if request.user.is_authenticated else False,
    }
    return render(request, "Home/stats.html",context={
        "additional_info":additional_info,
        "top":get_top_10()
    })

def teamView(request):
    additional_info = {
        "logged_in": True if request.user.is_authenticated else False
    }
    return render(request, "Home/team.html",{
        "additional_info":additional_info,
    })

Team/views.py
from django.shortcuts import render
from django.http import HttpResponse

def teamView(request):
    additional_info = {
        "logged_in": True if request.user.is_authenticated else False
    }
    return render(request, "Team/team.html",{
        "additional_info":additional_info,
    })

Accounts/templates/Accounts/login.html
{% extends 'base.html' %}{% load static %}
{% block wrapper %}
<div class="form-wrapper">
    <h3 class="web-name">Virdismart | Login</h3>
    <label class="errors"></label>
    <form class="login" action="/accounts/" method="post" autocomplete="off">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" class="token">
      <div class="input-field">
        <input type="email" name="email" class="username" placeholder="email" autocomplete="false">
      </div>
      <div class="input-field">
        <input type="password" name="password" class="password" placeholder="password" autocomplete="false">
      </div>
      <div class="input-field submit-btn">
        <button type="submit" name="submit" class="submit btn">login</button>
      </div>
    </form>

    <div class="account">Don't have an account?  <a href="{% url 'Accounts:signup' %}">signup</a></div>
  </div>
  <div class="loaders">
      <p class="loader-1"></p>
  </div>
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'Accounts/css/login.css' %}">
{% endblock %}
{% block js %}
  <script src="{% static 'Accounts/js/login.js' %}" charset="utf-8"></script>
{% endblock %}

Accounts/templates/Accounts/reset.html
{% extends 'base.html' %}{% load static %}
{% block wrapper %}

<div class="form-wrapper">
    <h4 class="web-name">Reset password</h4>
    <label class="errors"></label>
    <form class="login" action="/accounts/reset/" method="post" autocomplete="off">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" class="token">
      <div class="input-field">
        <input type="email" name="email" class="username" placeholder="your email" autocomplete="false">
      </div>
      <label class="infor"></label>
      <div class="input-field submit-btn">
        <button type="submit" name="submit" class="submit btn">reset</button>
      </div>
    </form>
  </div>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'Accounts/css/reset.css' %}">
{% endblock %}

{% block js %}
  <script src="{% static 'Accounts/js/reset.js' %}" charset="utf-8"></script>
{% endblock %}

Accounts/templates/Accounts/signup.html
{% extends 'base.html' %}{% load static %}
{% block wrapper %}
<div class="form-wrapper">
    <h3 class="web-name">Virdismart | Login</h3>
    <form class="login" action="/accounts/signup/" method="post" autocomplete="off">
      <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" class="token">
      <div class="input-field">
        <label class="errors email"></label>
        <input type="email" name="email" class="username" placeholder="email" autocomplete="false">
      </div>
      <div class="input-field">
        <label class="errors username"></label>
        <input type="username" name="username" class="username" placeholder="username" autocomplete="false">
      </div>
      <div class="input-field">
        <label class="errors password"></label>
        <input type="password" name="password1" class="password" placeholder="password" autocomplete="false">
      </div>
      <div class="input-field">
        <!-- <label class="errors password2"></label> -->
        <input type="password" name="password2" class="password" placeholder="password" autocomplete="false">
      </div>
      <div class="input-field submit-btn">
        <button type="submit" name="submit" class="submit btn">signup</button>
      </div>
    </form>
    <div class="account">Have an account?  <a href="{% url 'Accounts:account' %}">login</a></div>
  </div>
  <div class="loaders">
      <p class="loader-1"></p>
  </div>
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'Accounts/css/login.css' %}">
{% endblock %}
{% block js %}
  <script src="{% static 'Accounts/js/signup.js' %}" charset="utf-8"></script>
{% endblock %}

Asserts/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <meta name="keywords" content="smart,bin,smartbin,recycle,waste,enactus mmu,enactus,disposal,points,earn,virdismart,virdis">
    <meta name="lang" content="en">
    <meta charset="utf-8">
    <title>Virdismart Global</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'images/logos/icon.png' %}">
    <div class="loading">
        <img src="{% static 'images/logos/icon.png' %}" alt="logo">
    </div>
  </head>
  <body>
    <div class="menu-side">
      <p class="close-bar">&times;</p>
        <div class="">
            <div class="">
                <img src="{% static 'images/logos/virdis.png' %}" alt="virdis">
            </div>
            <div class="url-links">
              <a href="{% url 'home:home' %}">home &#8594;</a>
            </div>
            <div class="url-links">
                <a href="{% url 'home:team' %}" class="bout-us">team&#8594;</a>
            </div>
            <div class="url-links">
                <a href="#footer" class="contact-us">Contact us &#8594;</a>
            </div>
            {% if additional_info.logged_in %}
                <div class="url-links">
                  <a href="{% url 'Accounts:logout' %}">logout &#8594;</a>
                </div>
              {% else %}
              <div class="url-links">
                <a href="{% url 'Accounts:account' %}">login &#8594;</a>
              </div>
            {% endif %}
        </div>
    </div>
    <div class="wrap-body">
      <!-- navbar -->
        <div class="dev-navbar dev-nav">
              <div class="logo">
                  <img src="{% static 'images/logos/logo.png' %}" loading="lazy" alt="virdis" onclick="window.location.href='/'">
              </div>
              <div class="dev-link">
                <div class="our-impact">
                    <a href="{% url 'home:home' %}">home</a>
                </div>
                <div class="discover">
                    <a href="{% url 'home:team' %}">team</a>
                </div>
                {% if additional_info.logged_in %}
                <div class="login">
                  <a href="{% url 'Accounts:logout' %}">logout</a>
                </div>
                  {% else %}
                  <div class="login">
                    <a href="{% url 'Accounts:account' %}">login</a>
                  </div>
                {% endif %}
              </div>
        </div>
        <div class="navbar2 dev-nav">
          <div class="trigger-side">
            <span></span>
            <span></span>
            <span></span>
          </div>
            <div class="company">
                <h2>Virdismart</h2>
            </div>
        </div>
        {% block wrapper %}
        {% endblock %}
    </div>
    <div class="footer" id="footer">
        <hr>
          <div class="top-footer">
            <div class="main-footer virdis-social">
                <h4>Social Platform</h4>
                <div class="">
                    <a href="https://www.youtube.com/channel/UCt1nbPnduBIe8KuuNIxjnSA" target="_blank"> <i class="fa fa-youtube"></i> Youtube</a>
                </div>
                <div class="">
                    <a href="https://www.instagram.com/virdismart/"> <i class="fa fa-instagram" target="_blank"></i> Instagram</a>
                </div>
                <div class="">
                    <a href="https://www.linkedin.com/company/20478471/" target="_blank"><i class="fa fa-linkedin"></i>Linkedin</a>
                </div>
                <div class="">
                    <a href="https://twitter.com/virdismart" target="_blank"> <i class="fa fa-twitter"></i> Twitter</a>
                </div>
            </div>
            <div class="main-footer edison">
              “The value of an idea lies in the using of it.“ <br>
                  <b>Thomas Edison (1847 – 1931)</b>
            </div>
          </div>
          <hr class="horizontal">
      <div class="final">
        <a href="">www.virdis.co.ke</a>
        <a href="">info@virdis.co.ke</a>
        <a href=""> Call us: 0722 517 627</a>
      </div>
    </div>
    <div class="go-top">
        &#8593;
    </div>
  </body>
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  {% block css %}
  {% endblock %}
  {% block js %}
  {% endblock %}
  <script src="{% static 'js/base.js' %}" charset="utf-8"></script>
</html>

Home/templates/Home/home.html
{% extends 'base.html' %} {% load static %}
{% block wrapper %}
<div class="mcursor mouse"></div>
<div class="mcursor mouse1"></div>
<div class="page-wrapper">
          <div class="virdis-preview">
            <div class="prev-side">
              <h1>Turn your trash to cash with our smart bin</h1>
              <p>Drop your recycleables in our smartbin to get points which you can redeem for cash or discounts on selected products</p>
                <button type="button" name="button" class="stats">View stats</button>
            </div>
            <div class="arrow-down scroll-down">
                &#8595;
            </div>
          </div>
            <div class="group-1">
              <div class="more">
                <h1 class="topic-header-alt">Problem</h1>
                <div class="more-content">
                    <div class="spinner">
                        <p>Less than <br>
                              5% <br>
                        Recycling rate
                      </p>
                    </div>
                    <div class="description">
                        <h2 class="topic-header">Problem</h2>
                        <p>
                          Over 2,475 tons of waste is generated in
                          Nairobi daily. However, less than 5% is ecycled. The rest ends up in landfills or illegal dumping sites.
                        </p>
                    </div>
                </div>
              </div>
                    <div class="understand">
                      <div class="process-item">
                          <img src="{% static 'home/images/waste-truck.png' %}" alt="waste-truck">
                          <div class="process-info">
                            <h4>Collection</h4>
                              <p>
                                Waste is collected <br>
                                indiscriminately with <br>
                                only 5% being <br>
                                adequately sorted.
                              </p>
                          </div>
                      </div>
                      <div class="process-item">
                        <img src="{% static 'home/images/sorting.png' %}" alt="waste-truck">
                        <div class="process-info">
                          <h4>Sorting</h4>
                            <p>
                              Recyclable materials are often <br>mixed with health-hazardous <br>substances. This makes sorting <br>costly and time consuming.
                            </p>
                        </div>
                      </div>
                      <div class="process-item">
                        <img src="{% static 'home/images/recycling.png' %}" alt="waste-truck">
                        <div class="process-info">
                          <h4>Recycling</h4>
                            <p>
                              Contamination results in <br>recycling being a liability <br>
                              and less profitable <br>compared to producing <br>new materials.
                            </p>
                        </div>
                      </div>
                </div>
            </div>
            <div class="showcase group-2">
              <div class="understand-wrapper">
                <div class="proposition">
                  <h2 class="topic-header-alt">Value Proposition</h2>
                  <div class="prop-item">
                      <img src="{% static 'home/images/bin.png' %}">
                    </div>
                  <div class="description">
                    <h2 class="topic-header">Value Proposition</h2>
                    <p>
                        A Smart Recycling Bin that identifies waste disposed of  and rewards users with points that can be redeemed for cash or discount on products.
                    </p>
                  </div>
                </div>
                <div class="working">
                  <h1 class="topic-header-alt">How it works</h1>
                  <h1 class="topic-header">How it works</h1>
                  <div class="working-img">
                    <img src="{% static 'home/images/rec.png' %}">
                  </div>
                </div>
            </div>
                <div class="video">
                    <iframe width="640" height="360" src="https://www.youtube.com/embed/nUfPPrUCuLE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
                  <div class="user-inter">
                        <div class="content-wrapper">
                          <div class="proposition">
                            <div class="prop-item">
                                <img src="{% static 'home/images/woman.png' %}" alt="user">
                            </div>
                            <div class="description">
                              <h2 class="topic-header">The Smart Bin App</h2>
                                <p>
                                  Use your phone to find the nearest Smart Bin in your area to drop of your trash and earn points.
                                  Redeem your points for cash or discounts on products.
                                </p>
                            </div>
                          </div>
                        </div>
                      </div>
                        <div class="competitive">
                            <h2 class="topic-header">Competitve Advantage</h2>
                            <div class="advantage">
                              <div class="it-adv">
                                  <img src="{% static 'home/images/FIrstToMarket.png' %}" alt="first in market">
                                  <p>First to Market <br>using IoT on <br>Trash</p>
                              </div>
                              <div class="it-adv">
                                  <img src="{% static 'home/images/IP.png' %}" alt="IP">
                                  <p>Patented IP <br>Advantage</p>
                              </div>
                                <div class="it-adv">
                                    <img src="{% static 'home/images/EaseOfUse.png' %}" alt="ease of use">
                                    <p>Ease of use, <br>simply scan, <br>drop and earn</p>
                                </div>
                                <div class="it-adv">
                                    <img src="{% static 'home/images/community.png' %}" alt="community">
                                    <p>Community <br>Driven</p>
                                </div>
                            </div>
                        </div>
                        </div>
                      <!-- start here -->

                    <div class="group-3">
                      <div class="founders">
                          <h2 class="topic-header">Founders</h2>
                          <h1 class="topic-header-alt">Founders</h1>
                        <div class="f-profile">
                          <div class="f-1">
                              <img src="{% static 'home/images/eric.png' %}" alt="Paige Maina">
                              <div class="title">
                                  <h3>Eric M Mwirichia</h3>
                                  Co-Founder& CEO
                              </div>
                          </div>
                            <div class="f-1">
                                <img src="{% static 'home/images/team/lilian.png' %}" alt="Lilian Waita">
                                <div class="title">
                                    <h3>Lilian Waita</h3>
                                    Corporate Relation
                                </div>
                            </div>
							<div class='f-1'>
									<img src="{% static 'home/images/team/abby.png' %}" alt='Abby Chebet'>
									<div class='title'>
											<h3>Abby Chebet</h3>
											CFO
									</div>
							</div>
                        </div>
                      </div>
                      <div class="partners">
                        <h1 class="topic-header-alt">Partners</h1>
                          <h2 class="topic-header">Partners</h2>
                        <div class="partners-wrap">
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/ford.png' %}" alt="ford">
                            </div>
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/clinton.png' %}" alt="clinton">
                            </div>
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/enactus.png' %}" alt="enactus">
                            </div>
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/cress.png' %}" alt="cress">
                            </div>
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/mmu.png' %}" alt="mmu">
                            </div>
                            <div class="item-1">
                                  <img src="{% static 'home/images/sponsors/eden.png' %}" alt="eden">
                            </div>
                        </div>
                      </div>
                    </div>
</div>
{% endblock %}
<!-- resources links -->
{% block css %}
  <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
{% endblock %}
{% block js %}
  <script src="{% static 'home/js/home.js' %}" charset="utf-8"></script>
{% endblock %}

Home/templates/Home/stats.html
{% extends 'base.html' %} {% load static %}
{% block wrapper %}
  <div class="root">
    <div class="graph-data">
          <h2>Analitics</h2>
            <div class="mycanvas">
                <canvas id="analitics" width="300" height="300"></canvas>
            </div>
    </div>
    <div class="users-table">
        <h5>Top 10 users by points</h5>
        <table border="1">
            <tr>
                <th>Username</th>
                <th>Mass collected (g)</th>
                <th>Total points</th>
            </tr>
            {% for singleUser in top %}
              <tr>
                <td>{{singleUser.fname}} {{singleUser.lname}}</td>
                <td>{{singleUser.massThrown}}</td>
                <td>{{singleUser.points}}</td>
              </tr>
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock %}
{% block css %}
  <link rel="stylesheet" href="{% static 'home/css/stats.css' %}">
{% endblock %}
{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js" integrity="sha512-hZf9Qhp3rlDJBvAKvmiG+goaaKRZA6LKUO35oK6EsM0/kjPK32Yw7URqrq3Q+Nvbbt8Usss+IekL7CRn83dYmw==" crossorigin="anonymous"></script>
<script src="{% static 'home/js/stats.js' %}" charset="utf-8"></script>
{% endblock %}